name: Actualizar precios

on:
  schedule:
    - cron: "0 * * * *"   # cada 1 hora
  workflow_dispatch:      # permite ejecutarlo manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node scripts/updatePrices.js

      - name: Subir cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/productos.json
          git commit -m "Actualizar precios automáticamente" || echo "No hay cambios"
          git push
