name: Actualizar precios

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  actualizar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar actualización
        run: npm run actualizar-precios

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/productos.json
          git diff --staged --quiet || git commit -m "actualizar precios automaticamente"
          git push
